version: 2.1

jobs:
  test:  
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Install node pkgs
          command: cd ./src; npm install
      - run:
          name: Test
          command: cd ./src; npm run test

  sonar:
    docker:
      - image: sonarsource/sonar-scanner-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sonar-scanner \
                  -Dsonar.organization=olucasfagundes \
                  -Dsonar.projectKey=olucasfagundes_nodejs-demo-app \
                  -Dsonar.host.url=https://sonarcloud.io
                
workflows:
  test: 
    jobs:
      - test
  sonar:
    jobs:
      - sonar:
          context: SonarCloud