version: 2.1

orbs:
  node: circleci/node@4.4.0
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  test:  
    working_directory: ~/src
    docker:
      - image: cimg/node:16.2.0
    steps:
      - checkout
      - node/install-packages
      - run: 
          name: Test
          command: npm run test

  sonar:
    docker:
      - image: cimg/node:16.2.0
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/.src
      - sonarcloud/scan
      
workflows:
  test: 
    jobs:
      - test
  sonar:
    jobs:
      - sonar:
          context: SonarCloud