version: 2.1

orbs:
  node: circleci/node@4.1


jobs:
  test:  
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Install
          command: cd ./src && npm install
      - run:
          name: Test
          command: npm run test
      
workflows:
  test: 
    jobs:
      - test
