version: 2.1

orbs:
  node: circleci/node@4.1
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  test:  
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd ./src && npm install
      - run:
          name: Test
          command: cd ./src &&  npm run test

  sonar:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd ./src && apk add curl && npm install
      - sonarcloud/scan
      
workflows:
  test: 
    jobs:
      - test
  sonar:
    jobs:
      - sonar:
          context: SonarCloud