version: 2.1

orbs:
  docker: circleci/docker@1.6.0

jobs:
  test:  
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Install node pkgs
          command: cd ./src; npm install
      - run:
          name: Test
          command: cd ./src; npm run test

  lint:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Install node pkgs
          command: cd ./src; npm install
      - run:
          name: Lint
          command: cd ./src; npm run lint

  sonar:
    docker:
      - image: sonarsource/sonar-scanner-cli
    steps:
      - checkout
      - run:
          name: Sonar scan
          command: sonar-scanner
                
workflows:
  build: 
    jobs:
      - test
      - lint
      - sonar:
          context: SonarCloud
      - docker/hadolint:
          requires:
            - test
            - lint
            - sonar
      - docker/publish:
          context: DockerHub
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          update-description: true
          requires:
            - docker/hadolint
          
