version: 2.1

jobs:
  test:  
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Install node pkgs
          command: cd ./src; npm install
      - run:
          name: Test
          command: cd ./src; npm run test

  sonar:
    docker:
      - image: sonarsource/sonar-scanner-cli
    steps:
      - checkout
      - run:
          name: Sonar scan
          command: sonar-scanner
                
workflows:
  test: 
    jobs:
      - test
  sonar:
    jobs:
      - sonar:
          context: SonarCloud