version: 2.1

orbs:
  docker: circleci/docker@1.6.0

jobs:
  install-packages:  
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - run:
          name: Install node pkgs
          command: cd ./src; npm install
      - save_cache: 
          key: pkgs-{{ checksum "./src/package-lock.json" }}
          paths:
            - ./src

  test:  
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - restore_cache:
          keys: 
            - pkgs-{{ checksum "./src/package-lock.json" }}
      - run:
          name: Test
          command: cd ./src; npm run test

  lint:
    docker:
      - image: node:14-alpine
    steps:
      - checkout
      - restore_cache:
          keys: 
            - pkgs-{{ checksum "./src/package-lock.json" }}
      - run:
          name: Lint
          command: cd ./src; npm run lint

  sonar:
    docker:
      - image: sonarsource/sonar-scanner-cli
    steps:
      - checkout
      - run:
          name: Sonar scan
          command: sonar-scanner
          
  docker-security:
    docker:
      - image: docker:18.09-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image to check
          command: docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME .
      - run:
          name: Install AquaSec Trivy 
          command: |
            apk add --update-cache --upgrade --update curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Scan Docker Image for vulnerabilities
          command: trivy --exit-code 0 --no-progress $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
                
workflows:
  build: 
    jobs:
      - install-packages
      - test:
          requires:
            - install-packages
      - lint:
          requires:
            - install-packages
      - sonar:
          context: SonarCloud
      - docker/hadolint:
          requires:
            - test
            - lint
            - sonar
      - docker-security
      - docker/publish:
          context: DockerHub
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          requires:
            - docker-security